export { default as ManagePage } from './ManagePage';
export { default as ManageSide } from './ManageSide';
export { default as Hospitals } from './Hospitals';
export { default as Hospital } from './Hospital';
export { default as Floor } from './Floor';
export { default as Room } from './Room';
export { default as Patients } from './Patients';
export { default as Sensors } from './Sensors';
export { default as HospitalsList } from './HospitalsList';
export { default as FloorsList } from './FloorsList';
export * from './styles';
